name: Commit jars

on:
  workflow_run:
    workflows: Java CI with Gradle
    branches: main
    types: completed

jobs:
  build:
    if: ${{ (github.event.workflow_run.conclusion == 'success') && (github.ref == 'refs/heads/main') }}
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build with Gradle Wrapper
        run: ./gradlew jar

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: jars/matrix-solver-1.0.jar
          asset_name: matrix-solver.jar
          tag: ${{ github.ref }}
          overwrite: true
          body: "Read the readme file for details."
