name: Commit jars

on:
  workflow_run:
    workflows: Java CI with Gradle
    branches: main
    types: completed

jobs:
  build:
    if: ${{ (github.event.workflow_run.conclusion == 'success') && (github.ref == 'refs/heads/main') }}
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build with Gradle Wrapper
        run: ./gradlew jar

      - name: Commit jar
        run: |
          git config --global user.name 'Tobias Grothe'
          git config --global user.email 'tgrothe@users.noreply.github.com'
          git add -f jars
          git commit -m "Jar file added"
          git push
